name: Oxc Release Plz

description: Release Plz

inputs:
  PAT:
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0
        token: ${{ inputs.PAT }}
        persist-credentials: true # required by release-plz

    - uses: oxc-project/release-plz-action@12ee013e577af39a0b75f282e04064658afca86e # v1.0.1
      env:
        GITHUB_TOKEN: ${{ inputs.PAT }}
