name: Oxc Release Plz

description: Release Plz

inputs:
  PAT:
    description: "Personal Access Token for GitHub"
    required: true
    type: string

outputs:
  prs:
    description: "The release PRs opened by release-plz. (Not useful for now. Use `pr` instead)"
    value: ${{ steps.release-plz.outputs.prs }}
  pr:
    description: "The release PR opened by release-plz."
    value: ${{ steps.release-plz.outputs.pr }}
  releases:
    description: "The JSON output of the `release` command."
    value: ${{ steps.release-plz.outputs.releases }}
  prs_created:
    description: "Whether release-plz created any release PR."
    value: ${{ steps.release-plz.outputs.prs_created }}
  releases_created:
    description: "Whether release-plz released any package."
    value: ${{ steps.release-plz.outputs.releases_created }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        token: ${{ inputs.PAT }}
        persist-credentials: true # required by release-plz

    - uses: release-plz/action@adcc7904c46f9595dab7534d05c3fee773eac4bc # v0.5.122
      id: release-plz
      env:
        GITHUB_TOKEN: ${{ inputs.PAT }}
