name: Oxc Release Plz

description: Release Plz

inputs:
  PAT:
    description: "Personal Access Token for GitHub"
    required: true
    type: string

outputs:
  prs:
    description: "The release PRs opened by release-plz. (Not useful for now. Use `pr` instead)"
    value: ${{ steps.release-plz.outputs.prs }}
  pr:
    description: "The release PR opened by release-plz."
    value: ${{ steps.release-plz.outputs.pr }}
  releases:
    description: "The JSON output of the `release` command."
    value: ${{ steps.release-plz.outputs.releases }}
  prs_created:
    description: "Whether release-plz created any release PR."
    value: ${{ steps.release-plz.outputs.prs_created }}
  releases_created:
    description: "Whether release-plz released any package."
    value: ${{ steps.release-plz.outputs.releases_created }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0
        token: ${{ inputs.PAT }}
        persist-credentials: true # required by release-plz

    - uses: release-plz/action@e8792575c7f2366cf6ff3ccc33ead9ace5b691c7 # v0.5.130
      id: release-plz
      env:
        GITHUB_TOKEN: ${{ inputs.PAT }}
