name: Oxc Release Plz

description: Release Plz

inputs:
  PAT:
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      with:
        fetch-depth: 0
        token: ${{ inputs.PAT }}
        persist-credentials: true # required by release-plz

    - uses: oxc-project/setup-rust@cd82e1efec7fef815e2c23d296756f31c7cdc03d # v1.0.0
      with:
        restore-cache: false

    - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: changes
      with:
        filters: |
          src:
            - 'Cargo.toml'
            - '**/Cargo.toml'

    - uses: rust-lang/crates-io-auth-action@e919bc7605cde86df457cf5b93c5e103838bd879 # v1.0.1
      if: steps.changes.outputs.src == 'true'
      id: auth

    - uses: MarcoIeni/release-plz-action@ccf6dd998441f26020f4315f1ebe95d9e2e42600 # v0.5.110
      env:
        GITHUB_TOKEN: ${{ inputs.PAT }}
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
